// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ8fLGI4tPDjIj97piVwYttYANYJ3B_5g',
    appId: '1:951448646284:web:f0506b433598236ee801a9',
    messagingSenderId: '951448646284',
    projectId: 'finwise-a8f67',
    authDomain: 'finwise-a8f67.firebaseapp.com',
    storageBucket: 'finwise-a8f67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCskdW2sCud3ft3XELrI9a3GjvDYQbT4MM',
    appId: '1:951448646284:android:de02e11a011793fbe801a9',
    messagingSenderId: '951448646284',
    projectId: 'finwise-a8f67',
    storageBucket: 'finwise-a8f67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFTJs7odrbFAudly_vPuJzZ_S0bNF1QqQ',
    appId: '1:951448646284:ios:860433d6510bc3d3e801a9',
    messagingSenderId: '951448646284',
    projectId: 'finwise-a8f67',
    storageBucket: 'finwise-a8f67.firebasestorage.app',
    iosBundleId: 'com.example.finwiseHackayhon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFTJs7odrbFAudly_vPuJzZ_S0bNF1QqQ',
    appId: '1:951448646284:ios:860433d6510bc3d3e801a9',
    messagingSenderId: '951448646284',
    projectId: 'finwise-a8f67',
    storageBucket: 'finwise-a8f67.firebasestorage.app',
    iosBundleId: 'com.example.finwiseHackayhon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ8fLGI4tPDjIj97piVwYttYANYJ3B_5g',
    appId: '1:951448646284:web:801f5443a7505361e801a9',
    messagingSenderId: '951448646284',
    projectId: 'finwise-a8f67',
    authDomain: 'finwise-a8f67.firebaseapp.com',
    storageBucket: 'finwise-a8f67.firebasestorage.app',
  );
}
